name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Tidy
        run: go mod tidy

      - name: Build and Test
        run: |
          go build -v -o hammerclock.exe cmd/hammerclock/main.go
          go test -v ./...

      - name: Build for Windows
        env:
          GOOS: windows
          GOARCH: amd64
        run: go build -v -o hammerclock.exe cmd/hammerclock/main.go

      - name: Build for Linux
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -v -o hammerclock cmd/hammerclock/main.go

      - name: Build for Intel Mac
        env:
          GOOS: darwin
          GOARCH: amd64
        run: go build -v -o hammerclock-darwin-amd64 cmd/hammerclock/main.go

      - name: Build for Apple Silicon Mac
        env:
          GOOS: darwin
          GOARCH: arm64
        run: go build -v -o hammerclock-darwin-arm64 cmd/hammerclock/main.go

      - name: Publish Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: hammerclock-windows-amd64
          path: ./hammerclock.exe

      - name: Publish Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: hammerclock-linux-amd64
          path: ./hammerclock

      - name: Publish Intel Mac artifact
        uses: actions/upload-artifact@v4
        with:
          name: hammerclock-darwin-amd64
          path: ./hammerclock-darwin-amd64

      - name: Publish Apple Silicon Mac artifact
        uses: actions/upload-artifact@v4
        with:
          name: hammerclock-darwin-arm64
          path: ./hammerclock-darwin-arm64