name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Tidy
        run: go mod tidy

      - name: Build for Windows
        env:
          GOOS: windows
          GOARCH: amd64
        run: go build -v -o hammerclock.exe cmd/hammerclock/main.go

      - name: Build for Linux
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -v -o hammerclock cmd/hammerclock/main.go

      - name: Build for Intel Mac
        env:
          GOOS: darwin
          GOARCH: amd64
        run: go build -v -o hammerclock cmd/hammerclock/main.go

      - name: Build for Apple Silicon Mac
        env:
          GOOS: darwin
          GOARCH: arm64
        run: go build -v -o hammerclock cmd/hammerclock/main.go

      - name: Test
        run: go test -v ./...

      - name: Publish built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hammerclock
          path: ./